# Generated by Django 2.1.5 on 2020-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190908_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/', verbose_name='Иконка категории'),
        ),
        migrations.AddField(
            model_name='collection',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/', verbose_name='Иконка категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_img/', verbose_name='Иконка категории'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия безлимитного кода'),
        ),
    ]
