# Generated by Django 3.0.5 on 2020-10-01 14:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200503_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название звезды')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('seoText', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст для СЕО')),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звезды',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Спец. коллекция'),
        ),
        migrations.AddField(
            model_name='item',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Star'),
        ),
    ]
